import type { RequestStatus, RequestPriority, RequestCategory, AppRole, SupportRequest } from '@/types/database';

// Generate 30 days of analytics data
export const mockAnalytics = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  const metrics = ['requests_submitted', 'requests_resolved', 'avg_response_time', 'active_cases'];
  const metric = metrics[i % 4];
  
  let baseValue = 0;
  switch (metric) {
    case 'requests_submitted':
      baseValue = Math.floor(Math.random() * 20) + 5;
      break;
    case 'requests_resolved':
      baseValue = Math.floor(Math.random() * 15) + 3;
      break;
    case 'avg_response_time':
      baseValue = Math.floor(Math.random() * 48) + 2;
      break;
    case 'active_cases':
      baseValue = Math.floor(Math.random() * 50) + 20;
      break;
  }
  
  return {
    id: `analytics-${i + 1}`,
    date: date.toISOString().split('T')[0],
    metric,
    value: baseValue,
    change_percent: Math.round((Math.random() * 40 - 20) * 10) / 10,
  };
});

// Mock profiles for case managers
export const mockCaseManagers = [
  {
    id: 'cm-1',
    user_id: 'cm-user-1',
    email: 'david.chen@university.edu',
    full_name: 'David Chen',
    avatar_url: null,
    phone: '+1 555-0101',
    preferred_language: 'en',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    active_requests: 12,
    emergency_requests: 2,
    avg_response_time: 4.2,
  },
  {
    id: 'cm-2',
    user_id: 'cm-user-2',
    email: 'sarah.johnson@university.edu',
    full_name: 'Sarah Johnson',
    avatar_url: null,
    phone: '+1 555-0102',
    preferred_language: 'en',
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
    active_requests: 8,
    emergency_requests: 1,
    avg_response_time: 3.5,
  },
  {
    id: 'cm-3',
    user_id: 'cm-user-3',
    email: 'miguel.rodriguez@university.edu',
    full_name: 'Miguel Rodriguez',
    avatar_url: null,
    phone: '+1 555-0103',
    preferred_language: 'es',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
    active_requests: 15,
    emergency_requests: 3,
    avg_response_time: 5.1,
  },
  {
    id: 'cm-4',
    user_id: 'cm-user-4',
    email: 'emily.watson@university.edu',
    full_name: 'Emily Watson',
    avatar_url: null,
    phone: '+1 555-0104',
    preferred_language: 'en',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
    active_requests: 6,
    emergency_requests: 0,
    avg_response_time: 2.8,
  },
  {
    id: 'cm-5',
    user_id: 'cm-user-5',
    email: 'james.wilson@university.edu',
    full_name: 'James Wilson',
    avatar_url: null,
    phone: '+1 555-0105',
    preferred_language: 'en',
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-02-10T10:00:00Z',
    active_requests: 10,
    emergency_requests: 1,
    avg_response_time: 4.0,
  },
];

// Mock student profiles
export const mockStudents = [
  {
    id: 'student-1',
    user_id: 'student-user-1',
    email: 'aisha.khan@student.university.edu',
    full_name: 'Aisha Khan',
    avatar_url: null,
    phone: '+1 555-1001',
    preferred_language: 'en',
    created_at: '2024-09-01T10:00:00Z',
    updated_at: '2024-09-01T10:00:00Z',
  },
  {
    id: 'student-2',
    user_id: 'student-user-2',
    email: 'carlos.martinez@student.university.edu',
    full_name: 'Carlos Martinez',
    avatar_url: null,
    phone: '+1 555-1002',
    preferred_language: 'es',
    created_at: '2024-09-05T10:00:00Z',
    updated_at: '2024-09-05T10:00:00Z',
  },
  {
    id: 'student-3',
    user_id: 'student-user-3',
    email: 'jessica.lee@student.university.edu',
    full_name: 'Jessica Lee',
    avatar_url: null,
    phone: '+1 555-1003',
    preferred_language: 'en',
    created_at: '2024-09-10T10:00:00Z',
    updated_at: '2024-09-10T10:00:00Z',
  },
];

// Mock support requests (15 items)
export const mockRequests: SupportRequest[] = [
  {
    id: 'req-1',
    student_id: 'student-user-1',
    assigned_case_manager_id: 'cm-user-1',
    category: 'academic',
    priority: 'high',
    status: 'in_progress',
    title: 'Course Registration Issue',
    description: 'Unable to register for required courses due to prerequisite conflict. Need urgent help as registration deadline is approaching.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-18T14:30:00Z',
    updated_at: '2024-01-19T09:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[0],
    case_manager: mockCaseManagers[0],
  },
  {
    id: 'req-2',
    student_id: 'student-user-2',
    assigned_case_manager_id: 'cm-user-2',
    category: 'financial',
    priority: 'emergency',
    status: 'escalated',
    title: 'Financial Aid Emergency',
    description: 'My financial aid was unexpectedly cancelled and I cannot pay for housing. Need immediate assistance.',
    is_emergency: true,
    escalated_at: '2024-01-19T16:00:00Z',
    resolved_at: null,
    created_at: '2024-01-17T10:00:00Z',
    updated_at: '2024-01-19T16:00:00Z',
    requested_amount: 5000,
    approved_amount: null,
    student: mockStudents[1],
    case_manager: mockCaseManagers[1],
  },
  {
    id: 'req-3',
    student_id: 'student-user-3',
    assigned_case_manager_id: 'cm-user-3',
    category: 'mental_health',
    priority: 'high',
    status: 'in_progress',
    title: 'Counseling Appointment Request',
    description: 'Experiencing high levels of stress and anxiety. Would like to schedule an appointment with a counselor.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-16T11:00:00Z',
    updated_at: '2024-01-18T14:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[2],
    case_manager: mockCaseManagers[2],
  },
  {
    id: 'req-4',
    student_id: 'student-user-1',
    assigned_case_manager_id: 'cm-user-1',
    category: 'housing',
    priority: 'medium',
    status: 'submitted',
    title: 'Room Change Request',
    description: 'Requesting a room change due to ongoing issues with current roommate. Have tried to resolve through RA.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-20T09:00:00Z',
    updated_at: '2024-01-20T09:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[0],
    case_manager: mockCaseManagers[0],
  },
  {
    id: 'req-5',
    student_id: 'student-user-2',
    assigned_case_manager_id: 'cm-user-4',
    category: 'academic',
    priority: 'low',
    status: 'resolved',
    title: 'Transcript Request',
    description: 'Need official transcript for graduate school application.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: '2024-01-15T12:00:00Z',
    created_at: '2024-01-10T08:00:00Z',
    updated_at: '2024-01-15T12:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[1],
    case_manager: mockCaseManagers[3],
  },
  {
    id: 'req-6',
    student_id: 'student-user-3',
    assigned_case_manager_id: null,
    category: 'other',
    priority: 'medium',
    status: 'submitted',
    title: 'Parking Permit Issue',
    description: 'Received a parking ticket but I have a valid permit. Need help disputing the ticket.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-21T07:30:00Z',
    updated_at: '2024-01-21T07:30:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[2],
    case_manager: undefined,
  },
  {
    id: 'req-7',
    student_id: 'student-user-1',
    assigned_case_manager_id: 'cm-user-5',
    category: 'financial',
    priority: 'high',
    status: 'in_progress',
    title: 'Scholarship Application Help',
    description: 'Need assistance with completing department scholarship application. Deadline is next week.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-19T13:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
    requested_amount: 2500,
    approved_amount: null,
    student: mockStudents[0],
    case_manager: mockCaseManagers[4],
  },
  {
    id: 'req-8',
    student_id: 'student-user-2',
    assigned_case_manager_id: 'cm-user-1',
    category: 'mental_health',
    priority: 'emergency',
    status: 'in_progress',
    title: 'Crisis Support Needed',
    description: 'Experiencing a personal crisis and need immediate support resources.',
    is_emergency: true,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-21T02:00:00Z',
    updated_at: '2024-01-21T06:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[1],
    case_manager: mockCaseManagers[0],
  },
  {
    id: 'req-9',
    student_id: 'student-user-3',
    assigned_case_manager_id: 'cm-user-2',
    category: 'housing',
    priority: 'low',
    status: 'resolved',
    title: 'Maintenance Request Follow-up',
    description: 'Following up on maintenance request submitted two weeks ago for broken heater.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: '2024-01-18T16:00:00Z',
    created_at: '2024-01-12T14:00:00Z',
    updated_at: '2024-01-18T16:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[2],
    case_manager: mockCaseManagers[1],
  },
  {
    id: 'req-10',
    student_id: 'student-user-1',
    assigned_case_manager_id: 'cm-user-3',
    category: 'academic',
    priority: 'medium',
    status: 'in_progress',
    title: 'Academic Advisor Meeting',
    description: 'Need to meet with academic advisor to discuss changing major.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-17T15:00:00Z',
    updated_at: '2024-01-19T11:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[0],
    case_manager: mockCaseManagers[2],
  },
  {
    id: 'req-11',
    student_id: 'student-user-2',
    assigned_case_manager_id: 'cm-user-4',
    category: 'financial',
    priority: 'medium',
    status: 'submitted',
    title: 'Payment Plan Request',
    description: 'Would like to set up a payment plan for remaining tuition balance.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-20T11:00:00Z',
    updated_at: '2024-01-20T11:00:00Z',
    requested_amount: 3500,
    approved_amount: null,
    student: mockStudents[1],
    case_manager: mockCaseManagers[3],
  },
  {
    id: 'req-12',
    student_id: 'student-user-3',
    assigned_case_manager_id: 'cm-user-5',
    category: 'other',
    priority: 'low',
    status: 'cancelled',
    title: 'Event Space Booking',
    description: 'Need to book event space for student organization meeting.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-08T09:00:00Z',
    updated_at: '2024-01-10T09:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[2],
    case_manager: mockCaseManagers[4],
  },
  {
    id: 'req-13',
    student_id: 'student-user-1',
    assigned_case_manager_id: 'cm-user-2',
    category: 'housing',
    priority: 'high',
    status: 'escalated',
    title: 'Emergency Housing Needed',
    description: 'Lost housing due to building emergency. Need temporary accommodation.',
    is_emergency: true,
    escalated_at: '2024-01-21T08:00:00Z',
    resolved_at: null,
    created_at: '2024-01-21T06:00:00Z',
    updated_at: '2024-01-21T08:00:00Z',
    requested_amount: 1200,
    approved_amount: null,
    student: mockStudents[0],
    case_manager: mockCaseManagers[1],
  },
  {
    id: 'req-14',
    student_id: 'student-user-2',
    assigned_case_manager_id: 'cm-user-1',
    category: 'academic',
    priority: 'medium',
    status: 'resolved',
    title: 'Grade Appeal',
    description: 'Appealing final grade in MATH 201. Believe there was a calculation error.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: '2024-01-14T14:00:00Z',
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2024-01-14T14:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[1],
    case_manager: mockCaseManagers[0],
  },
  {
    id: 'req-15',
    student_id: 'student-user-3',
    assigned_case_manager_id: null,
    category: 'mental_health',
    priority: 'medium',
    status: 'submitted',
    title: 'Support Group Information',
    description: 'Looking for information about support groups on campus.',
    is_emergency: false,
    escalated_at: null,
    resolved_at: null,
    created_at: '2024-01-21T10:00:00Z',
    updated_at: '2024-01-21T10:00:00Z',
    requested_amount: null,
    approved_amount: null,
    student: mockStudents[2],
    case_manager: undefined,
  },
];

// Mock appointments (8 items)
export const mockAppointments = [
  {
    id: 'apt-1',
    request_id: 'req-1',
    student_id: 'student-user-1',
    case_manager_id: 'cm-user-1',
    title: 'Course Registration Discussion',
    description: 'Review options for resolving prerequisite conflict',
    scheduled_at: '2024-01-22T10:00:00Z',
    duration_minutes: 30,
    meeting_link: 'https://meet.university.edu/cm1-apt1',
    status: 'scheduled',
    created_at: '2024-01-19T09:00:00Z',
    updated_at: '2024-01-19T09:00:00Z',
    student: mockStudents[0],
    case_manager: mockCaseManagers[0],
  },
  {
    id: 'apt-2',
    request_id: 'req-3',
    student_id: 'student-user-3',
    case_manager_id: 'cm-user-3',
    title: 'Initial Counseling Session',
    description: 'First meeting to discuss support options',
    scheduled_at: '2024-01-22T14:00:00Z',
    duration_minutes: 60,
    meeting_link: 'https://meet.university.edu/cm3-apt2',
    status: 'scheduled',
    created_at: '2024-01-18T14:00:00Z',
    updated_at: '2024-01-18T14:00:00Z',
    student: mockStudents[2],
    case_manager: mockCaseManagers[2],
  },
  {
    id: 'apt-3',
    request_id: 'req-7',
    student_id: 'student-user-1',
    case_manager_id: 'cm-user-5',
    title: 'Scholarship Application Review',
    description: 'Review completed application before submission',
    scheduled_at: '2024-01-23T11:00:00Z',
    duration_minutes: 45,
    meeting_link: 'https://meet.university.edu/cm5-apt3',
    status: 'scheduled',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
    student: mockStudents[0],
    case_manager: mockCaseManagers[4],
  },
  {
    id: 'apt-4',
    request_id: 'req-10',
    student_id: 'student-user-1',
    case_manager_id: 'cm-user-3',
    title: 'Major Change Consultation',
    description: 'Discuss requirements and timeline for changing major',
    scheduled_at: '2024-01-24T09:00:00Z',
    duration_minutes: 30,
    meeting_link: null,
    status: 'scheduled',
    created_at: '2024-01-19T11:00:00Z',
    updated_at: '2024-01-19T11:00:00Z',
    student: mockStudents[0],
    case_manager: mockCaseManagers[2],
  },
  {
    id: 'apt-5',
    request_id: 'req-5',
    student_id: 'student-user-2',
    case_manager_id: 'cm-user-4',
    title: 'Transcript Processing Follow-up',
    description: 'Confirm transcript was received by graduate school',
    scheduled_at: '2024-01-14T10:00:00Z',
    duration_minutes: 15,
    meeting_link: 'https://meet.university.edu/cm4-apt5',
    status: 'completed',
    created_at: '2024-01-13T12:00:00Z',
    updated_at: '2024-01-14T10:15:00Z',
    student: mockStudents[1],
    case_manager: mockCaseManagers[3],
  },
  {
    id: 'apt-6',
    request_id: 'req-9',
    student_id: 'student-user-3',
    case_manager_id: 'cm-user-2',
    title: 'Maintenance Issue Resolution',
    description: 'Confirm heater is now working properly',
    scheduled_at: '2024-01-18T15:00:00Z',
    duration_minutes: 15,
    meeting_link: null,
    status: 'completed',
    created_at: '2024-01-17T16:00:00Z',
    updated_at: '2024-01-18T15:15:00Z',
    student: mockStudents[2],
    case_manager: mockCaseManagers[1],
  },
  {
    id: 'apt-7',
    request_id: 'req-8',
    student_id: 'student-user-2',
    case_manager_id: 'cm-user-1',
    title: 'Crisis Support Check-in',
    description: 'Follow-up on crisis support provided',
    scheduled_at: '2024-01-22T16:00:00Z',
    duration_minutes: 30,
    meeting_link: 'https://meet.university.edu/cm1-apt7',
    status: 'scheduled',
    created_at: '2024-01-21T06:00:00Z',
    updated_at: '2024-01-21T06:00:00Z',
    student: mockStudents[1],
    case_manager: mockCaseManagers[0],
  },
  {
    id: 'apt-8',
    request_id: null,
    student_id: 'student-user-1',
    case_manager_id: 'cm-user-1',
    title: 'General Check-in',
    description: 'Quarterly check-in meeting',
    scheduled_at: '2024-01-25T14:00:00Z',
    duration_minutes: 30,
    meeting_link: null,
    status: 'scheduled',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    student: mockStudents[0],
    case_manager: mockCaseManagers[0],
  },
];

// Mock offline drafts
export const mockOfflineDrafts = [
  {
    id: 'draft-1',
    user_id: 'student-user-1',
    draft_data: {
      category: 'academic' as RequestCategory,
      priority: 'medium' as RequestPriority,
      title: 'Course Override Request',
      description: 'Need override for COMP 301 - reached capacity but required for graduation.',
      is_emergency: false,
    },
    synced: false,
    created_at: '2024-01-21T08:00:00Z',
    updated_at: '2024-01-21T08:30:00Z',
  },
  {
    id: 'draft-2',
    user_id: 'student-user-1',
    draft_data: {
      category: 'financial' as RequestCategory,
      priority: 'high' as RequestPriority,
      title: 'Work-Study Position Inquiry',
      description: 'Looking for available work-study positions for spring semester.',
      is_emergency: false,
    },
    synced: true,
    created_at: '2024-01-20T12:00:00Z',
    updated_at: '2024-01-20T14:00:00Z',
  },
];

// Mock AI insights
export const mockAIInsights = [
  {
    id: 'insight-1',
    request_id: 'req-2',
    case_manager_id: 'cm-user-2',
    insight_type: 'suggestion',
    content: {
      title: 'Priority Financial Aid Case',
      message: 'This student has an urgent financial situation. Consider connecting with the Emergency Aid Fund coordinator.',
      action: 'Contact Emergency Aid',
      priority: 'high',
    },
    is_dismissed: false,
    created_at: '2024-01-19T16:30:00Z',
  },
  {
    id: 'insight-2',
    request_id: null,
    case_manager_id: 'cm-user-1',
    insight_type: 'weekly_summary',
    content: {
      title: 'Weekly Summary',
      message: 'You resolved 8 requests this week, a 20% increase from last week. Average response time improved to 4.2 hours.',
      stats: {
        resolved: 8,
        avg_response_time: 4.2,
        pending: 12,
      },
    },
    is_dismissed: false,
    created_at: '2024-01-21T00:00:00Z',
  },
  {
    id: 'insight-3',
    request_id: 'req-8',
    case_manager_id: 'cm-user-1',
    insight_type: 'alert',
    content: {
      title: 'Crisis Case Detected',
      message: 'This request mentions crisis keywords. Immediate attention recommended.',
      action: 'Review Immediately',
      priority: 'emergency',
    },
    is_dismissed: false,
    created_at: '2024-01-21T02:30:00Z',
  },
  {
    id: 'insight-4',
    request_id: null,
    case_manager_id: 'cm-user-3',
    insight_type: 'trend',
    content: {
      title: 'Mental Health Trend',
      message: '30% increase in mental health related requests this month. Consider proactive outreach.',
      category: 'mental_health',
      change: 30,
    },
    is_dismissed: false,
    created_at: '2024-01-20T12:00:00Z',
  },
];

// Dashboard stats helper
export function getDashboardStats(role: AppRole, userId?: string) {
  const userRequests = role === 'student' 
    ? mockRequests.filter(r => r.student_id === userId)
    : role === 'case_manager'
    ? mockRequests.filter(r => r.assigned_case_manager_id === userId)
    : mockRequests;

  return {
    totalRequests: userRequests.length,
    pendingRequests: userRequests.filter(r => r.status === 'submitted' || r.status === 'in_progress').length,
    resolvedRequests: userRequests.filter(r => r.status === 'resolved').length,
    emergencyRequests: userRequests.filter(r => r.is_emergency).length,
    escalatedRequests: userRequests.filter(r => r.status === 'escalated').length,
  };
}
