import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { OrgReport } from '@/hooks/useOrganizationReport';
import type { AISummaryResult } from '@/lib/reportAiSummary';
import { formatCurrency } from '@/lib/utils';

const FOREST: [number, number, number] = [5, 77, 59];
const SAGE: [number, number, number] = [136, 169, 140];
const RED: [number, number, number] = [180, 60, 60];

const fmtDate = (d: string) => format(new Date(d), 'PP');
const fmt = (d: string) => format(new Date(d), 'PP p');

function download(content: BlobPart, mime: string, filename: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return '';
  const s = String(v);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function csvSection(title: string, headers: string[], rows: unknown[][]) {
  return [
    title,
    headers.map(csvEscape).join(','),
    ...rows.map((r) => r.map(csvEscape).join(',')),
    '',
  ].join('\n');
}

export function orgReportFilename(r: OrgReport, ext: 'pdf' | 'csv') {
  const from = format(new Date(r.range.from), 'yyyy-MM-dd');
  const to = format(new Date(r.range.to), 'yyyy-MM-dd');
  return `evolve-org-report_${from}_${to}.${ext}`;
}

export function exportOrgReportCsv(r: OrgReport, ai?: AISummaryResult | null) {
  const parts: string[] = [];
  parts.push(
    csvSection(
      'Organization Report',
      ['Scope', 'From', 'To', 'Generated At', 'Generated By'],
      [[r.scopeLabel, fmtDate(r.range.from), fmtDate(r.range.to), fmt(r.generatedAt), 'Evolve Foundation']],
    ),
  );
  parts.push(
    csvSection(
      'Summary',
      ['Metric', 'Value'],
      [
        ['Students in scope', r.summary.studentCount],
        ['Requests opened', r.summary.requestsOpened],
        ['Requests resolved', r.summary.requestsResolved],
        ['Unresolved', r.summary.unresolvedCount],
        ['Open emergencies', r.summary.emergencyOpen],
        ['Avg resolution (hrs)', r.summary.avgResolutionHours],
        ['Notes in range', r.summary.notesInRange],
        ['Appointments scheduled', r.summary.appointmentsInRange],
        ['Appointments kept', r.summary.appointmentsKept],
        ['Attendance rate', r.summary.attendanceRate == null ? '' : `${Math.round(r.summary.attendanceRate * 100)}%`],
        ['Check-ins in range', r.summary.checkInsInRange],
        ['Surveys sent', r.summary.surveysSent],
        ['Surveys completed', r.summary.surveysCompleted],
      ],
    ),
  );
  parts.push(
    csvSection(
      'Life Skills Progress',
      ['Module', 'Title', 'Pre', 'Post', 'Delta', 'Pre n', 'Post n'],
      r.lifeSkills.modules.map((m) => [
        `M${String(m.module.number).padStart(2, '0')}`,
        m.module.title,
        m.preAvg == null ? '' : m.preAvg.toFixed(2),
        m.postAvg == null ? '' : m.postAvg.toFixed(2),
        m.delta == null ? '' : m.delta.toFixed(2),
        m.preN,
        m.postN,
      ]),
    ),
  );
  parts.push(
    csvSection(
      'Expanded Impact Metrics',
      ['Metric', 'Value'],
      [
        ['Certifications earned in range', r.impactMetrics.certifications.earnedInRange],
        ['Certifications active', r.impactMetrics.certifications.active],
        ['Certifications expiring ≤30d', r.impactMetrics.certifications.expiringSoon],
        ['Referrals created', r.impactMetrics.referrals.createdInRange],
        ['Referrals clicked', r.impactMetrics.referrals.clickedInRange],
        ['Post-grad plans on file', r.impactMetrics.milestones.plansOnFile],
        ['Graduations in range', r.impactMetrics.milestones.graduationsInRange],
        ['Plans stalled ≥30d', r.impactMetrics.milestones.stalled],
        ['Employed', r.impactMetrics.employmentReadiness.employed],
        ['Seeking', r.impactMetrics.employmentReadiness.seeking],
        ['Employment unknown', r.impactMetrics.employmentReadiness.unknown],
        ['M05 workforce readiness (post)', r.impactMetrics.employmentReadiness.m05PostAvg == null ? '' : r.impactMetrics.employmentReadiness.m05PostAvg.toFixed(2)],
      ],
    ),
  );
  parts.push(
    csvSection(
      'Risks & Next Steps',
      ['Severity', 'Risk / Action', 'Detail'],
      [
        ...r.risks.map((x) => [x.severity, x.label, x.detail]),
        ...r.actionItems.map((a) => [a.severity, 'ACTION: ' + a.text, '']),
      ],
    ),
  );
  parts.push(
    csvSection(
      'Top Unresolved',
      ['Title', 'Student', 'Priority', 'Status', 'Age (days)', 'Emergency'],
      r.topUnresolved.map((u) => [u.title, u.student_name || '', u.priority, u.status, u.ageDays, u.is_emergency ? 'yes' : 'no']),
    ),
  );
  if (ai) {
    parts.push(
      csvSection(
        'AI Summary (Recommendations)',
        ['Section', 'Content'],
        [
          ['Headline', ai.headline],
          ['Trends', ai.trends],
          ['Improvements', ai.improvements],
          ['Risk areas', ai.risk_areas],
          ['Recommended next steps', ai.next_steps],
          ['Generated at', ai.generated_at],
          ['Model', ai.model || ''],
        ],
      ),
    );
  }
  download('\ufeff' + parts.join('\n'), 'text/csv;charset=utf-8', orgReportFilename(r, 'csv'));
}

export function exportOrgReportPdf(r: OrgReport, ai?: AISummaryResult | null) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...FOREST);
  doc.rect(0, 0, pageWidth, 70, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Evolve Foundation', 40, 32);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Organization Report', 40, 52);

  doc.setTextColor(40, 40, 40);
  doc.setFontSize(10);
  doc.text(
    `${r.scopeLabel}  •  ${fmtDate(r.range.from)} – ${fmtDate(r.range.to)}  •  Generated ${fmt(r.generatedAt)}`,
    40,
    90,
  );

  autoTable(doc, {
    startY: 100,
    head: [['Summary', 'Value']],
    body: [
      ['Students in scope', String(r.summary.studentCount)],
      ['Requests opened', String(r.summary.requestsOpened)],
      ['Requests resolved', String(r.summary.requestsResolved)],
      ['Unresolved', String(r.summary.unresolvedCount)],
      ['Open emergencies', String(r.summary.emergencyOpen)],
      ['Avg resolution (hrs)', String(r.summary.avgResolutionHours)],
      ['Notes in range', String(r.summary.notesInRange)],
      ['Appointments (scheduled / kept)', `${r.summary.appointmentsInRange} / ${r.summary.appointmentsKept}`],
      ['Attendance rate', r.summary.attendanceRate == null ? '—' : `${Math.round(r.summary.attendanceRate * 100)}%`],
      ['Check-ins in range', String(r.summary.checkInsInRange)],
      ['Surveys (sent / completed)', `${r.summary.surveysSent} / ${r.summary.surveysCompleted}`],
    ],
    headStyles: { fillColor: FOREST },
    theme: 'striped',
    styles: { fontSize: 10 },
  });

  autoTable(doc, {
    head: [['Life Skills — Module', 'Pre', 'Post', 'Delta', 'Pre n', 'Post n']],
    body: r.lifeSkills.modules.map((m) => [
      `M${String(m.module.number).padStart(2, '0')} · ${m.module.title}`,
      m.preAvg == null ? '—' : m.preAvg.toFixed(2),
      m.postAvg == null ? '—' : m.postAvg.toFixed(2),
      m.delta == null ? '—' : m.delta.toFixed(2),
      m.preN,
      m.postN,
    ]),
    headStyles: { fillColor: FOREST },
    theme: 'striped',
    styles: { fontSize: 9 },
  });

  autoTable(doc, {
    head: [['Impact Metric', 'Value']],
    body: [
      ['Certifications earned in range', String(r.impactMetrics.certifications.earnedInRange)],
      ['Certifications active', String(r.impactMetrics.certifications.active)],
      ['Certifications expiring ≤30d', String(r.impactMetrics.certifications.expiringSoon)],
      ['Referrals created / clicked', `${r.impactMetrics.referrals.createdInRange} / ${r.impactMetrics.referrals.clickedInRange}`],
      ['Plans on file / stalled ≥30d', `${r.impactMetrics.milestones.plansOnFile} / ${r.impactMetrics.milestones.stalled}`],
      ['Graduations in range', String(r.impactMetrics.milestones.graduationsInRange)],
      ['Employment (E/S/U)', `${r.impactMetrics.employmentReadiness.employed} / ${r.impactMetrics.employmentReadiness.seeking} / ${r.impactMetrics.employmentReadiness.unknown}`],
      ['M05 workforce readiness (post)', r.impactMetrics.employmentReadiness.m05PostAvg == null ? '—' : r.impactMetrics.employmentReadiness.m05PostAvg.toFixed(2)],
    ],
    headStyles: { fillColor: SAGE },
    theme: 'striped',
    styles: { fontSize: 9 },
  });

  if (r.risks.length > 0) {
    autoTable(doc, {
      head: [['Severity', 'Risk', 'Detail']],
      body: r.risks.map((x) => [x.severity.toUpperCase(), x.label, x.detail]),
      headStyles: { fillColor: RED },
      theme: 'striped',
      styles: { fontSize: 9 },
    });
  }

  if (r.actionItems.length > 0) {
    autoTable(doc, {
      head: [['Severity', 'Recommended Next Step']],
      body: r.actionItems.map((a) => [a.severity.toUpperCase(), a.text]),
      headStyles: { fillColor: FOREST },
      theme: 'striped',
      styles: { fontSize: 9 },
    });
  }

  if (r.topUnresolved.length > 0) {
    autoTable(doc, {
      head: [['Title', 'Student', 'Priority', 'Status', 'Age (d)']],
      body: r.topUnresolved.map((u) => [
        u.title + (u.is_emergency ? '  ⚠' : ''),
        u.student_name || '',
        u.priority,
        u.status,
        String(u.ageDays),
      ]),
      headStyles: { fillColor: FOREST },
      theme: 'striped',
      styles: { fontSize: 9 },
    });
  }

  if (ai) {
    autoTable(doc, {
      head: [['AI Summary & Recommendations', '']],
      body: [
        ['Headline', ai.headline],
        ['Trends', ai.trends],
        ['Improvements', ai.improvements],
        ['Risk areas', ai.risk_areas],
        ['Recommended next steps', ai.next_steps],
      ],
      headStyles: { fillColor: FOREST },
      theme: 'grid',
      styles: { fontSize: 9, cellWidth: 'wrap', valign: 'top' },
      columnStyles: { 0: { cellWidth: 130, fontStyle: 'bold' }, 1: { cellWidth: 'auto' } },
    });
    const afterY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 0;
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(
      `AI-generated on ${format(new Date(ai.generated_at), 'PP p')}${ai.model ? ' · ' + ai.model : ''} — grounded in the report metrics above.`,
      40,
      afterY + 14,
    );
    doc.setTextColor(40, 40, 40);
  }


  const pageCount = doc.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(
      `Confidential • Generated by Evolve Foundation • Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 20,
      { align: 'center' },
    );
  }

  doc.save(orgReportFilename(r, 'pdf'));
}
