import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { InteractionReport } from '@/hooks/useInteractionReport';
import type { AISummaryResult } from '@/lib/reportAiSummary';
import { formatCurrency } from '@/lib/utils';

const slug = (s: string | null | undefined) =>
  (s || 'case-manager').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export function reportFilename(r: InteractionReport, ext: 'pdf' | 'csv') {
  const from = format(new Date(r.range.from), 'yyyy-MM-dd');
  const to = format(new Date(r.range.to), 'yyyy-MM-dd');
  return `evolve-report_${slug(r.caseManager?.full_name || r.caseManager?.email)}_${from}_${to}.${ext}`;
}

const fmt = (d: string) => format(new Date(d), 'PP p');
const fmtDate = (d: string) => format(new Date(d), 'PP');

function downloadBlob(content: BlobPart, mime: string, filename: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function csvEscape(value: unknown): string {
  if (value === null || value === undefined) return '';
  const s = String(value);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function toCsvSection(title: string, headers: string[], rows: unknown[][]): string {
  const lines: string[] = [];
  lines.push(title);
  lines.push(headers.map(csvEscape).join(','));
  rows.forEach((r) => lines.push(r.map(csvEscape).join(',')));
  lines.push('');
  return lines.join('\n');
}

export function exportReportCsv(r: InteractionReport, ai?: AISummaryResult | null) {
  const sections: string[] = [];
  sections.push(
    toCsvSection(
      'Report Header',
      ['Organization', 'Case Manager', 'Email', 'From', 'To', 'Generated At', 'Generated By'],
      [[
        r.organization?.name || '',
        r.caseManager?.full_name || '',
        r.caseManager?.email || '',
        fmtDate(r.range.from),
        fmtDate(r.range.to),
        fmt(r.generatedAt),
        'Evolve Foundation',
      ]],
    ),
  );


  sections.push(
    toCsvSection(
      'Summary',
      ['Metric', 'Value'],
      [
        ['Active students', r.summary.activeStudents],
        ['Requests opened', r.summary.requestsOpened],
        ['Requests resolved', r.summary.requestsResolved],
        ['Avg resolution (hrs)', r.summary.avgResolutionHours],
        ['Unresolved', r.summary.unresolvedCount],
        ['Emergency', r.summary.emergencyCount],
      ],
    ),
  );

  sections.push(
    toCsvSection(
      'Student Contacts',
      ['Messages sent', 'Messages received', 'Distinct students contacted'],
      [[r.contacts.messagesSent, r.contacts.messagesReceived, r.contacts.distinctStudents]],
    ),
  );

  sections.push(
    toCsvSection(
      'Notes Added',
      ['Note Type', 'Count'],
      [
        ['Total', r.notes.total],
        ...Object.entries(r.notes.byType).map(([k, v]) => [k, v]),
      ],
    ),
  );

  sections.push(
    toCsvSection(
      'Surveys',
      ['Sent', 'Completed'],
      [[r.surveys.sent, r.surveys.completed]],
    ),
  );

  sections.push(
    toCsvSection(
      'Financial Assistance',
      ['Metric', 'Value'],
      [
        ['Financial requests', r.financials.count],
        ['Total requested', formatCurrency(r.financials.requested)],
        ['Total approved (disbursed)', formatCurrency(r.financials.approved)],
        ['Pending', formatCurrency(r.financials.pending)],
        ['Approved count', r.financials.approvedCount],
        ['Partially approved count', r.financials.partiallyApprovedCount],
        ['Pending count', r.financials.pendingCount],
        ['Denied count', r.financials.deniedCount],
      ],
    ),
  );

  // Life Skills progress (module deltas)
  sections.push(
    toCsvSection(
      'Life Skills Progress',
      ['Module', 'Title', 'Pre avg', 'Post avg', 'Delta', 'Pre n', 'Post n'],
      r.lifeSkills.modules.map((m) => [
        `M${String(m.module.number).padStart(2, '0')}`,
        m.module.title,
        m.preAvg == null ? '' : m.preAvg.toFixed(2),
        m.postAvg == null ? '' : m.postAvg.toFixed(2),
        m.delta == null ? '' : m.delta.toFixed(2),
        m.preN,
        m.postN,
      ]),
    ),
  );

  // Expanded impact metrics
  sections.push(
    toCsvSection(
      'Expanded Impact Metrics',
      ['Metric', 'Value'],
      [
        ['Scope', r.impactMetrics.scopeLabel],
        ['Surveys sent', r.impactMetrics.surveys.sent],
        ['Surveys completed', r.impactMetrics.surveys.completed],
        ['Certifications earned in range', r.impactMetrics.certifications.earnedInRange],
        ['Certifications active', r.impactMetrics.certifications.active],
        ['Certifications expiring ≤30d', r.impactMetrics.certifications.expiringSoon],
        ['Referrals created', r.impactMetrics.referrals.createdInRange],
        ['Referrals clicked', r.impactMetrics.referrals.clickedInRange],
        ['Post-grad plans on file', r.impactMetrics.milestones.plansOnFile],
        ['Graduations in range', r.impactMetrics.milestones.graduationsInRange],
        ['Plans stalled ≥30d', r.impactMetrics.milestones.stalled],
        ['Employed', r.impactMetrics.employmentReadiness.employed],
        ['Seeking', r.impactMetrics.employmentReadiness.seeking],
        ['Employment unknown', r.impactMetrics.employmentReadiness.unknown],
        ['M05 workforce readiness (post)', r.impactMetrics.employmentReadiness.m05PostAvg == null ? '' : r.impactMetrics.employmentReadiness.m05PostAvg.toFixed(2)],
      ],
    ),
  );

  sections.push(
    toCsvSection(
      'Requests Breakdown',
      ['Bucket', 'Key', 'Count'],
      [
        ['Status', 'Opened', r.requests.opened],
        ['Status', 'In progress', r.requests.inProgress],
        ['Status', 'Resolved', r.requests.resolved],
        ['Status', 'Escalated', r.requests.escalated],
        ...Object.entries(r.requests.byCategory).map(([k, v]) => ['Category', k, v]),
        ...Object.entries(r.requests.byPriority).map(([k, v]) => ['Priority', k, v]),
      ],
    ),
  );

  sections.push(
    toCsvSection(
      'Status Changes',
      ['Date', 'Request ID', 'From', 'To', 'Note'],
      r.statusChanges.map((s) => [
        fmt(s.created_at),
        s.request_id,
        s.previous_status || '',
        s.new_status || '',
        s.note || '',
      ]),
    ),
  );

  sections.push(
    toCsvSection(
      'Follow-ups (Meetings)',
      ['Scheduled', 'Title', 'Status', 'Duration (min)'],
      r.followUps.rows.map((a) => [fmt(a.scheduled_at), a.title, a.status, a.duration_minutes]),
    ),
  );

  sections.push(
    toCsvSection(
      'Unresolved Items',
      ['Created', 'Title', 'Student', 'Priority', 'Status'],
      r.unresolved.map((req) => [
        fmtDate(req.created_at),
        req.title,
        req.student?.full_name || '',
        req.priority,
        req.status,
      ]),
    ),
  );

  if (ai) {
    sections.push(
      toCsvSection(
        'AI Summary (Recommendations)',
        ['Section', 'Content'],
        [
          ['Headline', ai.headline],
          ['Trends', ai.trends],
          ['Improvements', ai.improvements],
          ['Risk areas', ai.risk_areas],
          ['Recommended next steps', ai.next_steps],
          ['Generated at', ai.generated_at],
          ['Model', ai.model || ''],
        ],
      ),
    );
  }

  downloadBlob('\ufeff' + sections.join('\n'), 'text/csv;charset=utf-8', reportFilename(r, 'csv'));
}

export function exportReportPdf(r: InteractionReport, ai?: AISummaryResult | null) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const orgName = r.organization?.name?.trim();

  // Header — organization name takes priority; Evolve attribution stays secondary
  doc.setFillColor(5, 77, 59); // Forest Green
  doc.rect(0, 0, pageWidth, 70, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(orgName || 'Evolve Foundation', 40, 32);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Case Manager Interaction Report', 40, 52);
  if (orgName) {
    doc.setFontSize(9);
    doc.setTextColor(220, 230, 220);
    doc.text('Powered by Evolve Foundation', pageWidth - 40, 32, { align: 'right' });
  }

  doc.setTextColor(40, 40, 40);
  doc.setFontSize(11);
  let y = 95;
  doc.setFont('helvetica', 'bold');
  doc.text(r.caseManager?.full_name || 'Unknown Case Manager', 40, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  y += 14;
  doc.text(r.caseManager?.email || '', 40, y);
  if (orgName) {
    y += 14;
    doc.text(`Organization: ${orgName}`, 40, y);
  }
  y += 14;
  doc.text(
    `Range: ${fmtDate(r.range.from)} – ${fmtDate(r.range.to)}    Generated: ${fmt(r.generatedAt)}`,
    40,
    y,
  );
  y += 10;


  autoTable(doc, {
    startY: y + 6,
    head: [['Metric', 'Value']],
    body: [
      ['Active students', r.summary.activeStudents],
      ['Requests opened', r.summary.requestsOpened],
      ['Requests resolved', r.summary.requestsResolved],
      ['Avg resolution (hrs)', r.summary.avgResolutionHours],
      ['Unresolved', r.summary.unresolvedCount],
      ['Emergency', r.summary.emergencyCount],
    ],
    headStyles: { fillColor: [5, 77, 59] },
    theme: 'striped',
    styles: { fontSize: 10 },
  });

  autoTable(doc, {
    head: [['Student Contacts', 'Count']],
    body: [
      ['Messages sent', r.contacts.messagesSent],
      ['Messages received', r.contacts.messagesReceived],
      ['Distinct students contacted', r.contacts.distinctStudents],
    ],
    headStyles: { fillColor: [136, 169, 140] },
    theme: 'striped',
    styles: { fontSize: 10 },
  });

  autoTable(doc, {
    head: [['Notes Added', 'Count']],
    body: [
      ['Total', r.notes.total],
      ...Object.entries(r.notes.byType).map(([k, v]) => [k, v]),
    ],
    headStyles: { fillColor: [136, 169, 140] },
    theme: 'striped',
    styles: { fontSize: 10 },
  });

  autoTable(doc, {
    head: [['Surveys', 'Count']],
    body: [
      ['Sent', r.surveys.sent],
      ['Completed', r.surveys.completed],
    ],
    headStyles: { fillColor: [136, 169, 140] },
    theme: 'striped',
    styles: { fontSize: 10 },
  });

  // Life Skills progress
  autoTable(doc, {
    head: [['Life Skills — Module', 'Pre', 'Post', 'Delta', 'Pre n', 'Post n']],
    body: r.lifeSkills.modules.map((m) => [
      `M${String(m.module.number).padStart(2, '0')} · ${m.module.title}`,
      m.preAvg == null ? '—' : m.preAvg.toFixed(2),
      m.postAvg == null ? '—' : m.postAvg.toFixed(2),
      m.delta == null ? '—' : m.delta.toFixed(2),
      m.preN,
      m.postN,
    ]),
    headStyles: { fillColor: [5, 77, 59] },
    theme: 'striped',
    styles: { fontSize: 9 },
  });

  // Expanded impact metrics
  autoTable(doc, {
    head: [['Impact Metric', 'Value']],
    body: [
      ['Scope', r.impactMetrics.scopeLabel],
      ['Certifications earned in range', String(r.impactMetrics.certifications.earnedInRange)],
      ['Certifications active', String(r.impactMetrics.certifications.active)],
      ['Certifications expiring ≤30d', String(r.impactMetrics.certifications.expiringSoon)],
      ['Referrals created / clicked', `${r.impactMetrics.referrals.createdInRange} / ${r.impactMetrics.referrals.clickedInRange}`],
      ['Plans on file / stalled ≥30d', `${r.impactMetrics.milestones.plansOnFile} / ${r.impactMetrics.milestones.stalled}`],
      ['Graduations in range', String(r.impactMetrics.milestones.graduationsInRange)],
      ['Employed / Seeking / Unknown', `${r.impactMetrics.employmentReadiness.employed} / ${r.impactMetrics.employmentReadiness.seeking} / ${r.impactMetrics.employmentReadiness.unknown}`],
      ['M05 workforce readiness (post)', r.impactMetrics.employmentReadiness.m05PostAvg == null ? '—' : r.impactMetrics.employmentReadiness.m05PostAvg.toFixed(2)],
    ],
    headStyles: { fillColor: [136, 169, 140] },
    theme: 'striped',
    styles: { fontSize: 9 },
  });

  autoTable(doc, {
    head: [['Requests', 'Bucket', 'Count']],
    body: [
      ['Status', 'Opened', r.requests.opened],
      ['Status', 'In progress', r.requests.inProgress],
      ['Status', 'Resolved', r.requests.resolved],
      ['Status', 'Escalated', r.requests.escalated],
      ...Object.entries(r.requests.byCategory).map(([k, v]) => ['Category', k, v]),
      ...Object.entries(r.requests.byPriority).map(([k, v]) => ['Priority', k, v]),
    ],
    headStyles: { fillColor: [5, 77, 59] },
    theme: 'striped',
    styles: { fontSize: 10 },
  });

  if (r.statusChanges.length) {
    autoTable(doc, {
      head: [['Date', 'From', 'To', 'Note']],
      body: r.statusChanges.map((s) => [
        fmt(s.created_at),
        s.previous_status || '—',
        s.new_status || '—',
        s.note || '',
      ]),
      headStyles: { fillColor: [5, 77, 59] },
      theme: 'striped',
      styles: { fontSize: 9, cellWidth: 'wrap' },
      columnStyles: { 3: { cellWidth: 220 } },
      didDrawPage: () => {
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
      },
    });
  }

  if (r.followUps.rows.length) {
    autoTable(doc, {
      head: [['Scheduled', 'Title', 'Status', 'Duration (min)']],
      body: r.followUps.rows.map((a) => [fmt(a.scheduled_at), a.title, a.status, a.duration_minutes]),
      headStyles: { fillColor: [5, 77, 59] },
      theme: 'striped',
      styles: { fontSize: 9 },
    });
  }

  if (r.unresolved.length) {
    autoTable(doc, {
      head: [['Created', 'Title', 'Student', 'Priority', 'Status']],
      body: r.unresolved.map((req) => [
        fmtDate(req.created_at),
        req.title,
        req.student?.full_name || '',
        req.priority,
        req.status,
      ]),
      headStyles: { fillColor: [180, 60, 60] },
      theme: 'striped',
      styles: { fontSize: 9 },
    });
  }

  if (ai) {
    autoTable(doc, {
      head: [['AI Summary & Recommendations', '']],
      body: [
        ['Headline', ai.headline],
        ['Trends', ai.trends],
        ['Improvements', ai.improvements],
        ['Risk areas', ai.risk_areas],
        ['Recommended next steps', ai.next_steps],
      ],
      headStyles: { fillColor: [5, 77, 59] },
      theme: 'grid',
      styles: { fontSize: 9, cellWidth: 'wrap', valign: 'top' },
      columnStyles: { 0: { cellWidth: 130, fontStyle: 'bold' }, 1: { cellWidth: 'auto' } },
    });
    const afterY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 0;
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(
      `AI-generated on ${format(new Date(ai.generated_at), 'PP p')}${ai.model ? ' · ' + ai.model : ''} — grounded in the report metrics above.`,
      40,
      afterY + 14,
    );
    doc.setTextColor(40, 40, 40);
  }

  // Footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(
      `Confidential • Generated by Evolve Foundation • Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 20,
      { align: 'center' },
    );
  }

  doc.save(reportFilename(r, 'pdf'));
}
