GRANT EXECUTE ON FUNCTION public.is_org_admin(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.is_org_admin_of(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.org_admin_orgs(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_in_org_admin_scope(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_in_org_admin_scope_v2(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_user_org_suspended(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_org_suspended(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_staff_manage_student(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_staff_access_request(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_user_role(uuid) TO authenticated, anon, service_role;